### ISSUE TITLE
update failed for AnAction with ID=lookupThesaurus: com/intellij/psi/impl/source/tree/ElementType

### ISSUE THREAD

**Issue by slessard** [pascaldevink/intellij-thesaurus#1]
Using AppCode version 2.0.1 (I'm not exactly sure which IDE version that maps to.) I get the below exception every time the Thesaurus plugin tries to run.

update failed for AnAction with ID=lookupThesaurus: com/intellij/psi/impl/source/tree/ElementType
java.lang.NoClassDefFoundError: com/intellij/psi/impl/source/tree/ElementType
    at net.tweakers.intellij.thesaurus.action.ThesaurusAction.getPsiElement(ThesaurusAction.java:87)
    at net.tweakers.intellij.thesaurus.action.ThesaurusAction.update(ThesaurusAction.java:71)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:100)
    at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:167)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:126)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:85)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:241)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:266)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:226)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1028)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1107)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:333)
    at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:215)
    at javax.swing.JMenu.setSelected(JMenu.java:294)
    at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1175)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:200)
    at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:100)
    at javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:495)
    at java.awt.Component.processMouseEvent(Component.java:6391)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6147)
    at java.awt.Container.processEvent(Container.java:2083)
    at java.awt.Component.dispatchEventImpl(Component.java:4744)
    at java.awt.Container.dispatchEventImpl(Container.java:2141)
    at java.awt.Component.dispatchEvent(Component.java:4572)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4619)
    at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4408)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4262)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4210)
    at java.awt.Container.dispatchEventImpl(Container.java:2127)
    at java.awt.Window.dispatchEventImpl(Window.java:2489)
    at java.awt.Component.dispatchEvent(Component.java:4572)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:710)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:669)
    at java.awt.EventQueue$2.run(EventQueue.java:667)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:683)
    at java.awt.EventQueue$3.run(EventQueue.java:681)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:680)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:686)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:507)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:334)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.impl.source.tree.ElementType PluginClassLoader[net.tweakers.intellij.thesaurus, 1.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 54 more

**Comment by pascaldevink** [comment]
I've been able to reproduce the issue. It seems like the selected entity is not recognised by any of the plugin's dependencies. I'll add the proper jar files when I get the time (or you can do it yourself and send a pull request).

**Comment by rafi** [comment]
I'm receiving the same exception with PhpStorm v6.0.1
I'd love to help, but I'm Java clueless.. 
Sounds like a really cool plugin though !

**Comment by b4mboo** [comment]
Same here on Rubymine 6.0.3 build 133.632.
Whatever I click, I get that error. I don't even know how that plugin is supposed to work as all I see from it is this Error message. :-/

**Comment by matthiasnoback** [comment]
@pascaldevink This seems like a very useful plugin, however: I get this exact same error when I try to use it. I think I'll be very happy if this problem would be fixed ;)

**Comment by nikita-vanyasin** [comment]
Have a same issue on PhpStorm 8.1
Can someone fix it?

**Comment by pascaldevink** [comment]
@slessard @rafi @b4mboo @matthiasnoback I've just pushed a new version of this plugin to the plugin repository, and the update is now under review. If accepted, that should fix this problem!

If you're very eager to try it out yourself, pull the latest changes from master or download 2.0 from the release page to build it yourself: https://github.com/pascaldevink/intellij-thesaurus/releases
You can also download compiled 2.0 plugin here: https://github.com/pascaldevink/intellij-thesaurus/releases/download/2.0/intellij-thesaurus.zip and install it as local plugin.

**Comment by matthiasnoback** [comment]
@pascaldevink Cool, thanks for the notification!

**Comment by matthiasnoback** [comment]
@pascaldevink I installed the compiled plugin in PHPStorm 9.0.2 and it gave this error:

```
cannot create class "nl.pascaldevink.intellij.thesaurus.action.ThesaurusAction" [Plugin: net.tweakers.intellij.thesaurus]
com.intellij.diagnostic.PluginException: cannot create class "nl.pascaldevink.intellij.thesaurus.action.ThesaurusAction" [Plugin: net.tweakers.intellij.thesaurus]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:176)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:516)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:496)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:489)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1310)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1303)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1303)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1318)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1318)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1297)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.c(ActionManagerImpl.java:1285)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:76)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1268)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: com.intellij.diagnostic.PluginException: nl/pascaldevink/intellij/thesaurus/action/ThesaurusAction : Unsupported major.minor version 52.0 [Plugin: net.tweakers.intellij.thesaurus]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
    ... 23 more
Caused by: java.lang.UnsupportedClassVersionError: nl/pascaldevink/intellij/thesaurus/action/ThesaurusAction : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 29 more
```

**Comment by pascaldevink** [comment]
@matthiasnoback did you compile it yourself, install it from the release file or install in from the plugin repository (the latest version is on there now)

**Comment by matthiasnoback** [comment]
@pascaldevink I installed this one: https://github.com/pascaldevink/intellij-thesaurus/releases/download/2.0/intellij-thesaurus.zip
I'll try the one from the plugin repository now.

**Comment by matthiasnoback** [comment]
@pascaldevink Same problem...

**Comment by pascaldevink** [comment]
@matthiasnoback which version of java are you running? 7 or 8?

**Comment by matthiasnoback** [comment]
@pascaldevink Java runtime seems to have version 1.6 (maybe that's the problem? :))

**Comment by pascaldevink** [comment]
@matthiasnoback yes, unfortunately. I compiled this plugin with JDK 8, which is not backwards compatible (as in, it can not build backward compatible artifacts).
Besides, I though PHPStorm 9 now requires at least JDK (or JRE) 7? Seems interesting that you can still start it with 1.6.

Please try to upgrade to the latest version and try again :smile:

**Comment by matthiasnoback** [comment]
@pascaldevink I upgraded to 8. It doesn't give an error anymore, but it doesn't seem to do anything as well. It just shows the menu option "Thesaurus", greyed out. Any suggestions?

**Comment by pascaldevink** [comment]
@matthiasnoback I finally got around to updating the documentation. Take a look at the README and the updated description of the plugin in the repository.
I'm going to close this issue, as the original issue was resolved. If there's anything that you still encounter, please open a new issue :)

**Comment by matthiasnoback** [comment]
@pascaldevink Thanks for the update - it works!
